'use client';
import type { SampleProgress } from '../lib/sample-loading';
import { enterClubAudio } from '../lib/audio-entry';
import { SAMPLE_CATALOG } from '../lib/sample-catalog';
import { useEffect, useRef, useState } from 'react';
import { AudioLines, Headphones, Volume2, VolumeX, Users, Copy, Check, X, Zap, Radio, Trophy } from 'lucide-react';
import { ClubStage } from './components/club-stage';
import { LayerBadge } from './components/layer-badge';
import { layerMix, type LayerId } from '../lib/layers';
import type { Room, Choice } from '../lib/game';
import type { ScheduledClubAudio } from '../lib/scheduled-club-audio';
import { presentScene, ServerClock } from '../lib/music-timeline';
import { styleForRound } from '../lib/music-styles';
type View = Omit<Room,'total'|'endAfterRound'|'choices'|'players'> & { revision:number; players:{id:string;name:string;score:number;layer?:LayerId}[]; me:string; myChoice:Choice; serverNow:number };
type Session = {code:string;token:string};
const fmt = (n:number) => n.toLocaleString(undefined,{maximumFractionDigits:1});
const colors = ['#b5ff5b','#ba9cff','#ff9b70','#76dfff','#f5ce62','#f484c4','#92edba','#b0bbff'];
export default function Game() {
  const [serverRoom,setRoom]=useState<View|null>(null), [session,setSession]=useState<Session|null>(null);
  const [sampleProgress,setSampleProgress]=useState<SampleProgress|null>(null);
  const [name,setName]=useState(''),[code,setCode]=useState('');
  const [help,setHelp]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[connected,setConnected]=useState(true);
  const [audioReady,setAudioReady]=useState(false),[muted,setMuted]=useState(false),[copied,setCopied]=useState(false),[clock,setClock]=useState(Date.now()),[draft,setDraft]=useState<Choice|null>(null);
  const audio=useRef<ScheduledClubAudio|null>(null), offset=useRef(0), serial=useRef(0), applied=useRef(0), choiceQueue=useRef<Promise<unknown>>(Promise.resolve());
  const current=useRef<View|null>(null), serverClock=useRef(new ServerClock());
  const room=serverRoom?presentScene(serverRoom,clock+offset.current):null;
  function accept(next:View, requestId:number, sent:number) {
    if(current.current?.code===next.code && (next.revision<current.current.revision || (next.revision===current.current.revision && requestId<applied.current)))return; applied.current=requestId;
    offset.current=serverClock.current.sample(sent,Date.now(),next.serverNow);current.current=next;setRoom(next);setConnected(true);
  }
  useEffect(()=>{
    const qs=new URLSearchParams(location.search).get('room'); if(qs){setCode(qs.toUpperCase());}
    try { const raw=sessionStorage.getItem('drop-dj'); if(raw){const saved=JSON.parse(raw);if(!qs||saved.code===qs.toUpperCase())setSession(saved);} } catch{}
    let frame:number;const animate=()=>{setClock(Date.now());frame=requestAnimationFrame(animate);};frame=requestAnimationFrame(animate);return()=>{cancelAnimationFrame(frame);audio.current?.dispose();};
  },[]);
  useEffect(()=>{
    if(!session)return; let canceled=false;let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{
      const sent=Date.now(),id=++serial.current;
      try{const res=await fetch(`/api/game?code=${session.code}`,{headers:{'X-DJ-Token':session.token},cache:'no-store'});const data=await res.json() as View & {error?:string};if(!res.ok)throw new Error(data.error);if(!canceled)accept(data,id,sent);}
      catch(e){if(!canceled){setConnected(false);setError(e instanceof Error?e.message:'Reconnecting to the club…');}}
      if(!canceled){const r=current.current;const remaining=r?r.deadline-Date.now()-offset.current:Infinity;timer=setTimeout(poll,r&&(r.phase==='landing'||r.phase==='choice'&&remaining<1500)?100:500);}
    };poll();return()=>{canceled=true;clearTimeout(timer);};
  },[session]);
  useEffect(()=>{setDraft(null);},[room?.game,room?.round,room?.phase]);
  useEffect(()=>{
    const a=audio.current;if(!a||!serverRoom)return;
    a.offset=offset.current;
    const latest=serverRoom.history.at(-1),result=latest?.round===serverRoom.round?latest:undefined;
    a.sync({...serverRoom,result});
  },[serverRoom,audioReady]);
  const seconds=room?Math.max(0,Math.ceil((room.deadline-clock-offset.current)/1000)):0;
  async function enterAudio(){setBusy(true);setError('');try{setSampleProgress({completed:0,total:SAMPLE_CATALOG.length,failed:0});await enterClubAudio(audio,setSampleProgress);setAudioReady(true);return true;}catch{setError('Sound could not start. Tap again to retry.');return false;}finally{setBusy(false);}}
  async function action(action:string,extra:Record<string,unknown>={}) {
    const sent=Date.now(),id=++serial.current;
    const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json',...(session?{'X-DJ-Token':session.token}:{})},body:JSON.stringify({action,code:session?.code||code,name,...extra})});
    const data=await res.json() as {room:View;token?:string;error?:string};if(!res.ok)throw new Error(data.error||'Try again.');
    if(data.token){const s={code:data.room.code,token:data.token};setSession(s);sessionStorage.setItem('drop-dj',JSON.stringify(s));history.replaceState(null,'',`?room=${s.code}`);}
    accept(data.room,id,sent);return data;
  }
  async function submit(actionName:string){setBusy(true);setError('');try{if(!audioReady){if(!await enterAudio())return;setBusy(true);}await action(actionName);}catch(e){setError(e instanceof Error?e.message:'Try again.');}finally{setBusy(false);}}
  function choose(choice:Choice){if(!room||room.phase!=='choice'||!connected||seconds===0)return;setDraft(choice);const round=room.round,game=room.game;choiceQueue.current=choiceQueue.current.catch(()=>{}).then(()=>action('choice',{choice,round,game})).then(()=>setDraft(prev=>prev===choice?null:prev)).catch(e=>{setDraft(null);setError(e.message);});}
  async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/?room=${room!.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError('Copy the room code or the link from your address bar.');}}
  const result=room?.history.at(-1), selected=draft||room?.myChoice||'BUILD';
  const ranked=room?[...room.players].sort((a,b)=>b.score-a.score):[];
  const leaders=ranked.filter(p=>p.score===ranked[0]?.score);
  const soundLayers=[{energy:20,label:'Kick'},{energy:40,label:'Hi-hats'},{energy:60,label:'Bass'},{energy:80,label:'Synths'},{energy:100,label:'Full drop'}];
  const currentLayer=room&&room.energy>0?Math.max(0,soundLayers.findLastIndex(layer=>room.energy>=layer.energy)):-1;
  const showMoment=room?.phase==='reveal'&&result&&(result.outcome==='CRASH'||result.outcome==='DROP');
  const impact=room?.phase==='reveal'&&result?.outcome==='DROP'?clock+offset.current-result.at:Infinity;
  const style=room?styleForRound(room.game,room.round):null;
  const mix=room?layerMix(room.players,room.history,room.round+(room.phase==='reveal'||room.phase==='ended'?1:0)):null;
  const mine=room?.players.find(p=>p.id===room.me);
  const beatOrigin=room?.phase==='choice'?room.deadline+1000:room?.phase==='landing'?room.deadline:result?.at??0;
  const floor=room&&style&&room.phase!=='lobby'?<ClubStage energy={room.energy} bpm={style.bpm} origin={beatOrigin} offset={offset.current} result={room.phase==='reveal'?result:undefined}/>:null;
  const spotlight=room?.phase==='reveal'&&result?<div className="layer-spotlights" aria-label="Layer changes for the next round">{room.players.map(p=><div className={`layer-spotlight ${p.layer&&mix?.[p.layer]?'layer-in':'layer-cut'}`} key={p.id}><strong>{p.name}</strong><LayerBadge layer={p.layer}/><span>{p.layer&&mix?.[p.layer]?'COMING IN':'CUTTING OUT'}</span></div>)}</div>:null;
  return <div className={`shell ${impact>=0&&impact<400?'drop-shake':''}`}>
    <header><a className="brand" href="/" aria-label="DROP DILEMMA home"><AudioLines size={26}/><span>DROP<span className="brand-light"> DILEMMA</span></span></a><div className="header-actions"><button className="text-button" onClick={()=>setHelp(true)}>How to play</button>{audioReady&&<button className="icon-button" aria-label={muted?'Unmute sound':'Mute sound'} onClick={()=>{setMuted(!muted);audio.current?.mute(!muted);}}>{muted?<VolumeX size={20}/>:<Volume2 size={20}/>}</button>}</div></header>
    {sampleProgress&&sampleProgress.completed<sampleProgress.total&&<div className="sample-loading" role="status" aria-live="polite"><span>Loading sounds {sampleProgress.completed}/{sampleProgress.total}</span><progress aria-label="Club sounds loaded" value={sampleProgress.completed} max={sampleProgress.total}/></div>}
    {audioReady&&sampleProgress&&sampleProgress.failed>0&&<p className="sample-fallback" role="status">Some sounds could not load. Backup sounds are playing.</p>}
    {!room?<main className="join-layout"><section className="join-intro"><div className="eyebrow">THE NEXT SET STARTS WITH YOU</div><h1>Trust your crew.<br/><span>Maybe.</span></h1><p className="intro">Build together for a bigger crowd.<br/>Drop to turn that energy into points.<br/>Too many drops? Everyone loses.</p><div className="fact-row"><span><Users size={18}/>2–8 players</span><span><Radio size={18}/>Live beats + synths</span></div></section>
      <section className="panel join-panel"><h2>Get your crew on stage</h2><label htmlFor="dj">Your DJ name</label><input id="dj" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. DJ Midnight" maxLength={24} required autoComplete="nickname"/>
        <div className="start-option"><p>Hosting the party?</p><button type="button" className="primary" disabled={busy||!name.trim()} onClick={()=>submit('create')}>Create a room</button></div>
        <form className="start-option join-option" onSubmit={e=>{e.preventDefault();submit('join');}}><h2>Already have an invite?</h2><label htmlFor="code">Room code</label><input id="code" className="code-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))} placeholder="ABCDE" maxLength={5} minLength={5} required autoComplete="off"/><button type="submit" className="primary join-button" disabled={busy||!name.trim()||code.length!==5}>Join a room</button></form>
        {!audioReady&&<button type="button" className="secondary start-audio" disabled={busy} onClick={enterAudio}><Headphones size={18}/>{busy?'Connecting…':'Tap to enter the club'}</button>}<p className="subtle">Creating or joining enables sound.<br/>Everyone plays on their own phone or laptop.</p></section></main>:<main className="game-layout">
      <section className="stage">
        <div className="room-bar"><div><span className="eyebrow">ROOM CODE</span><strong className="room-code">{room.code}</strong></div><button className="secondary" onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Copied':'Invite friends'}</button></div>
        {!showMoment&&floor}
        {mine?.layer&&<div className="your-layer"><span>Your part of the track</span><LayerBadge layer={mine.layer} active={mix?.[mine.layer]}/><p>BUILD keeps your part playing. DROP cuts it out next round.</p></div>}
        {!audioReady&&<button className="secondary start-audio" disabled={busy} onClick={enterAudio}><Headphones size={18}/>Tap to enter the club · Enable sound</button>}
        {!connected&&<div className="connection" role="status">Connection lost. Reconnecting… Your last saved choice still counts.</div>}
        {room.phase==='lobby'?<div className="lobby"><div className="eyebrow">BACKSTAGE</div><h1>Your crew.<br/><span>Your dilemma.</span></h1><p>Share the code or invite link. Everyone needs their own device.</p><div className="dj-list">{room.players.map((p,i)=><div className="dj-chip" key={p.id}><span className="avatar" style={{background:colors[i],color:'#121410'}}>{p.name[0].toUpperCase()}</span><span>{p.name}{p.id===room.me?' (you)':''}</span>{p.id===room.host&&<small>HOST</small>}</div>)}</div>{room.me===room.host?<button className="primary" disabled={busy||room.players.length<2} onClick={()=>submit('start')}>{room.players.length<2?'Waiting for another DJ':`Start the set · ${room.players.length} DJs`}</button>:<p className="waiting">Waiting for the host to start the set…</p>}<p className="subtle">15-second choices · A secret ending · Highest score wins</p></div>:room.phase==='ended'?<div className="end"><div className="eyebrow"><Trophy size={17}/> SET COMPLETE</div><h1>{leaders.length>1?'Shared spotlight.':'The spotlight is yours.'}</h1><p className="winner">{leaders.map(p=>p.name).join(' & ')} <span>· {fmt(leaders[0].score)} points</span></p><h2>Every choice, revealed</h2><div className="history-wrap"><table><thead><tr><th>DJ</th>{room.history.map(r=><th key={r.round}>{r.round}</th>)}</tr></thead><tbody>{room.players.map(p=><tr key={p.id}><th>{p.name}</th>{room.history.map(r=><td key={r.round}><span className={`history-choice ${r.choices.find(c=>c.id===p.id)!.choice.toLowerCase()}`} title={`Round ${r.round}: ${r.choices.find(c=>c.id===p.id)!.choice}`}>{r.choices.find(c=>c.id===p.id)!.choice==='BUILD'?'B':'D'}</span></td>)}</tr>)}</tbody></table></div><p className="subtle">B = BUILD · D = DROP</p><div className="theory"><h2>Why trust gets tricky</h2><p><strong>Prisoner’s dilemma.</strong> Your temptation to take points competes with the group’s benefit from building. This is a multiplayer variation of that tension.</p><p><strong>Tragedy of the commons.</strong> The crowd is a shared resource. Too many DJs cashing in at once destroy it for everyone.</p><p><strong>Random continuation.</strong> After the first five guaranteed rounds, each completed round has a 75% chance of another round. Without an announced final round, there is no visible deadline from which to work backward. Future rewards and the chance to rebuild trust can encourage cooperation, though they don’t guarantee it.</p></div>{room.me===room.host?<button className="primary" disabled={busy} onClick={()=>submit('rematch')}>Play another set</button>:<p>Waiting for the host to start a rematch.</p>}</div>:<>
          <div className="round-heading"><div><div className="eyebrow">{room.phase==='choice'?'MAKE YOUR MOVE':room.phase==='landing'?'CHOICES LOCKED':'THE CREW HAS SPOKEN'}</div><h1>Round {room.round}</h1><p className="music-style">{style?.name} · {style?.bpm} BPM</p></div>{room.phase==='choice'&&seconds<=3&&seconds>0&&<div className="predrop-countdown" aria-hidden="true"><strong>{seconds}</strong><span>GET READY</span></div>}<div className={`timer ${seconds<=3?'urgent':''}`} aria-label={`${seconds} seconds remaining`}><strong>{String(seconds).padStart(2,'0')}</strong><span>{room.phase==='choice'?'TO LOCK':room.phase==='landing'?'DROP INCOMING':'NEXT UP'}</span></div></div>
          <div className={`energy-panel ${room.energy===0?'silent':''}`}><div className="energy-top"><span>CROWD ENERGY</span><strong>{fmt(room.energy)}<small> / 100</small></strong></div><div className="energy-meter" role="progressbar" aria-label="Crowd energy" aria-valuenow={room.energy} aria-valuemin={0} aria-valuemax={100}>{Array.from({length:25},(_,i)=><i className={i*4<room.energy?'lit':''} key={i}/>)}</div><div className="energy-bottom"><span>{room.energy===0?'Silence. Time to rebuild.':room.energy<40?'Kick + pad + soft slap bass':room.energy<60?'Kick + pad + hi-hats':room.energy<80?'Bass is in':room.energy<100?'Synths + build sweep':'Full drop ready'}</span><AudioLines size={20}/></div>
            <ol className="sound-layers" aria-label="Sound layer milestones">{soundLayers.map((layer,i)=><li key={layer.energy} className={i===currentLayer?'current':i<currentLayer?'unlocked':'locked'} aria-current={i===currentLayer?'step':undefined}><span>{layer.energy}: {layer.label}</span><small>{i===currentLayer?'Current':i<currentLayer?'Unlocked':i===currentLayer+1?'Next':'Locked'}</small></li>)}</ol><p className="sound-hint">{room.energy===0?'Rebuild to bring back the kick and soft pad.':room.energy===100?'A successful DROP at 100 adds the full-drop chord hit.':'Energy unlocks richer sounds. Each owner’s last revealed choice controls whether their part is in the mix.'}</p></div>
          {room.phase==='choice'?<><p className="choice-prompt">Shared energy. A personal decision.</p><div className="choices"><button className={`choice build ${selected==='BUILD'?'selected':''}`} disabled={!connected||seconds===0} onClick={()=>choose('BUILD')}><span className="choice-icon"><AudioLines/></span><strong>BUILD</strong><span>Give the crowd +10 energy</span><small>{selected==='BUILD'?<><Check size={15}/> {draft?'Saving…':'Selected · stays secret'}</>:'Keep the club alive'}</small></button><button className={`choice drop ${selected==='DROP'?'selected':''}`} disabled={!connected||seconds===0} onClick={()=>choose('DROP')}><span className="choice-icon"><Zap/></span><strong>DROP</strong><span>Cash in shared energy</span><small>{selected==='DROP'?<><Check size={15}/> {draft?'Saving…':'Selected · stays secret'}</>:'Too many drops crash the crowd'}</small></button></div><p className="subtle choice-note">Change your mind until the timer ends. No choice = BUILD.<br/>Up to {Math.floor(room.players.length/2)} Droppers can score. {Math.floor(room.players.length/2)+1} or more causes a crash.</p></>:room.phase==='landing'?<div className="locked-note" role="status">Choices locked · drop incoming</div>:result&&<div className={`reveal ${result.outcome.toLowerCase()}`} aria-live="polite"><h2>{result.outcome==='CRASH'?'CROWD CRASH':result.outcome==='DROP'?'THE DROP LANDED':'EVERYONE BUILT'}</h2><p>{result.outcome==='CRASH'?'Too many drops. No points. All energy wiped out.':result.outcome==='DROP'?`Droppers split ${fmt(result.before)} energy. Builders added their energy afterward.`:'Nobody cashed in. Your crowd keeps growing.'}</p><div className="reveal-list">{result.choices.map(c=><div className="reveal-row" key={c.id}><strong>{c.name}{c.id===room.me?' (you)':''}</strong><span className={`badge ${c.choice.toLowerCase()}`}>{c.choice}</span><span>+{fmt(c.points)} pts</span></div>)}</div><p className="subtle">Energy: {fmt(result.before)} → {fmt(result.after)}</p>{!showMoment&&spotlight}</div>}
        </>}
      </section><aside className="scoreboard panel"><div className="score-title"><h2>{room.phase==='ended'?'Final scores':'Scoreboard'}</h2><span>{room.players.length}/8 DJs</span></div><div className="scores">{ranked.map((p,i)=><div className={`score-row ${p.id===room.me?'you':''}`} key={p.id}><span className="rank">{i+1}</span><span className="avatar" style={{background:colors[room.players.findIndex(x=>x.id===p.id)],color:'#121410'}}>{p.name[0].toUpperCase()}</span><div className="score-name">{p.name}<LayerBadge layer={p.layer} active={p.layer?mix?.[p.layer]:undefined}/><small>{p.id===room.me?'YOU':p.id===room.host?'HOST':'DJ'}</small></div><strong>{fmt(p.score)}</strong></div>)}</div><div className="score-foot"><Headphones size={18}/><p>Build the energy.<br/>Read the room.</p></div></aside>
    </main>}
    {room?.phase==='landing'&&<div className="locked-moment" role="status"><strong>Choices locked</strong><span>drop incoming</span></div>}
    {impact>=0&&impact<180&&<div className="drop-flash" aria-hidden="true"/>}
    {showMoment&&<section className={`result-moment ${result.outcome.toLowerCase()}`} role="status" aria-live="polite" aria-atomic="true"><div className="moment-content">{floor}<div className="eyebrow">Round {room.round} · RESULT</div><h2>{result.outcome==='CRASH'?'CROWD CRASH':'DROP!'}</h2>{result.outcome==='CRASH'?<p className="moment-message">Too many DJs dropped. Energy wiped to 0.</p>:<div className="drop-takers">{result.choices.filter(c=>c.choice==='DROP').map(c=><p key={c.id}><strong>{c.name}</strong> cashed in <strong>{fmt(c.points)} {c.points===1?'point':'points'}</strong>.</p>)}</div>}<p className="moment-energy">{result.outcome==='CRASH'?'No points. Silence means rebuild.':`Crowd Energy: ${fmt(result.before)} → ${fmt(result.after)}`}</p><div className="moment-choices">{result.choices.map(c=><div key={c.id}><strong>{c.name}</strong><span className={`badge ${c.choice.toLowerCase()}`}>{c.choice}</span><span>+{fmt(c.points)} pts</span></div>)}</div>{spotlight}<p className="moment-countdown">Result phase ends in {seconds}s</p></div></section>}
    {error&&<div className="error-toast" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div>}
    <footer><span>ONE STAGE. NO GUARANTEES.</span><span>DROP DILEMMA <span className="footer-slash">/</span> A GAME OF TRUST</span></footer>
    {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help panel" role="dialog" aria-modal="true" aria-label="How to play" onClick={e=>e.stopPropagation()}><button className="close icon-button" aria-label="Close how to play" onClick={()=>setHelp(false)}><X/></button><div className="eyebrow">THE HOUSE RULES</div><h2>How to play</h2><p>2–8 DJs share a crowd starting at 20 energy. Each round, you have 15 seconds to secretly choose. Change your mind until time runs out; no choice means BUILD.</p><div className="rule"><span className="badge build">BUILD</span><p>Add +10 energy, up to 100. If everyone builds, no energy is lost.</p></div><div className="rule"><span className="badge drop">DROP</span><p>If no more than half drop, those DJs split the energy from the start of the round as points. Energy is halved, then Builders’ +10s are added.</p></div><div className="rule"><span className="badge crash">CRASH</span><p>If more than half drop, nobody scores. Energy becomes 0, including that round’s builds. Silence means rebuild.</p></div><p>Choices lock for one held-breath second, then names and choices reveal together for 5 seconds. Each DJ owns a musical part: BUILD keeps it playing next round; DROP cuts it out next round. Unowned core parts support smaller crews. Energy controls the intensity, and a crash silences everything. Highest score wins; exact ties share victory.</p><p>The first five rounds always happen. After each round from round five onward, there is a 25% chance the set ends. The server decides privately; you won’t know whether another round is coming.</p><p className="subtle">Disconnected? Rejoin on the same tab to keep your DJ identity. Missed choices default to BUILD. Use headphones to avoid a room full of overlapping speakers.</p><button className="primary" onClick={()=>setHelp(false)}>Got it</button></section></div>}
  </div>;
}
