// Generated by scripts/download-samples.mjs; pinned CC0 Sonic Pi assets.
export const SAMPLE_CATALOG=[
  {
    "id": "bd_808",
    "url": "/samples/bd_808.mp3",
    "group": "drums",
    "duration": 0.5597505668934241,
    "bytes": 7567,
    "sha256": "4a6cbd4f7b5cf0cc2f415bce5ac7dd90ea55f618db3e6bc9c88b5d91de7a029d",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/bd_808.flac"
  },
  {
    "id": "bd_haus",
    "url": "/samples/bd_haus.mp3",
    "group": "drums",
    "duration": 0.21993197278911564,
    "bytes": 3492,
    "sha256": "9eaa869e3f26bfdf05c3d9694c22ccc5d28ffd17228dc1e886b9f10b30c47c09",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/bd_haus.flac"
  },
  {
    "id": "bd_fat",
    "url": "/samples/bd_fat.mp3",
    "group": "drums",
    "duration": 0.23219954648526078,
    "bytes": 3492,
    "sha256": "23d13d73c339898068e7247036588a75e9a14b4b5fcc7b881515fa311f09eb65",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/bd_fat.flac"
  },
  {
    "id": "bd_boom",
    "url": "/samples/bd_boom.mp3",
    "group": "drums",
    "duration": 1.7142857142857142,
    "bytes": 21359,
    "sha256": "08f69134aa930e22ca930adcea7c9ff69ba6dd565f134913b3dbc6505b6e8176",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/bd_boom.flac"
  },
  {
    "id": "sn_dub",
    "url": "/samples/sn_dub.mp3",
    "group": "drums",
    "duration": 0.2781179138321995,
    "bytes": 4119,
    "sha256": "b2404e2333e3298880facddb25fa83bb67da125da6d6cac686fe353f66940489",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/sn_dub.flac"
  },
  {
    "id": "sn_dolf",
    "url": "/samples/sn_dolf.mp3",
    "group": "drums",
    "duration": 0.37759637188208617,
    "bytes": 5373,
    "sha256": "fa1cdb78c6bbc032817cb4a158c1dccf6434626535530091eae63ab67e802660",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/sn_dolf.flac"
  },
  {
    "id": "sn_generic",
    "url": "/samples/sn_generic.mp3",
    "group": "drums",
    "duration": 0.5454648526077097,
    "bytes": 7253,
    "sha256": "a2adf3753bd078653d1c88a4c88a40ba185d380e0e5fcd5484ab4448617dfe08",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/sn_generic.flac"
  },
  {
    "id": "hat_bdu",
    "url": "/samples/hat_bdu.mp3",
    "group": "drums",
    "duration": 0.09764172335600907,
    "bytes": 1924,
    "sha256": "f26d7993ce3dce7afa33680a224afaf19183f3d8d5d15b2f017162a21452f614",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/hat_bdu.flac"
  },
  {
    "id": "hat_cab",
    "url": "/samples/hat_cab.mp3",
    "group": "drums",
    "duration": 0.15666666666666668,
    "bytes": 2551,
    "sha256": "4dcfe2ef904892fb0c29d090da44352cce9ff91664e3304c27da9a0f89280ed7",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/hat_cab.flac"
  },
  {
    "id": "hat_gem",
    "url": "/samples/hat_gem.mp3",
    "group": "drums",
    "duration": 0.1319954648526077,
    "bytes": 2551,
    "sha256": "40fd73c37f7cf0a873fd72b0a8ffa3cc57f9c9c00d3482dde70a75600f5b826b",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/hat_gem.flac"
  },
  {
    "id": "hat_metal",
    "url": "/samples/hat_metal.mp3",
    "group": "drums",
    "duration": 0.9138548752834467,
    "bytes": 11642,
    "sha256": "decd70bde7b89674ee9ef8ac3850e9b62db28a8a09ee07c40b9c62865f782c3c",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/hat_metal.flac"
  },
  {
    "id": "hat_raw",
    "url": "/samples/hat_raw.mp3",
    "group": "drums",
    "duration": 0.2072108843537415,
    "bytes": 3178,
    "sha256": "88cbdbd8a402fa33c1467e2a4cdf9a65ec9747926bbbfeebf869db8577528acf",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/hat_raw.flac"
  },
  {
    "id": "hat_tap",
    "url": "/samples/hat_tap.mp3",
    "group": "drums",
    "duration": 0.17197278911564626,
    "bytes": 2865,
    "sha256": "76bbff37c8a35c6c0009382d4fd26fd173457a6f4f2b505a81db235220faf566",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/hat_tap.flac"
  },
  {
    "id": "drum_cymbal_open",
    "url": "/samples/drum_cymbal_open.mp3",
    "group": "drums",
    "duration": 1.8043764172335601,
    "bytes": 22613,
    "sha256": "0e1d1c11fc8ad5ac174c27feca4f5e089a22e2ac29e95ca5f94fadde2dfd2fce",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/drum_cymbal_open.flac"
  },
  {
    "id": "drum_roll",
    "url": "/samples/drum_roll.mp3",
    "group": "drums",
    "duration": 6.241678004535148,
    "bytes": 75590,
    "sha256": "54fa160309e91b8754b25c0703ab48951071fc4deac3d8772a3ed4a8e54c9287",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/drum_roll.flac"
  },
  {
    "id": "loop_amen",
    "url": "/samples/loop_amen.mp3",
    "group": "drums",
    "duration": 1.753310657596372,
    "bytes": 29300,
    "sha256": "74696afe3dcd90844fc4b481250c61abf7d988a30f47bed61792e8db86b7f847",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/loop_amen.flac"
  },
  {
    "id": "loop_breakbeat",
    "url": "/samples/loop_breakbeat.mp3",
    "group": "drums",
    "duration": 1.9047619047619047,
    "bytes": 31390,
    "sha256": "f63774d4edc35c0bbc845f6852fe01e0d73fd452c5f673ac1ed97b8a65f65d5a",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/loop_breakbeat.flac"
  },
  {
    "id": "loop_tabla",
    "url": "/samples/loop_tabla.mp3",
    "group": "percussion",
    "duration": 10.673990929705216,
    "bytes": 171824,
    "sha256": "d6d41e841c240b8d6352f443a23b928defd7dfa9edcd31e0c484e5c1400d1ac0",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/loop_tabla.flac"
  },
  {
    "id": "loop_safari",
    "url": "/samples/loop_safari.mp3",
    "group": "percussion",
    "duration": 8.005079365079364,
    "bytes": 129192,
    "sha256": "de0d0e21000b57b3a7cb97fa160a9ad1884e18438599f8ed86f8d50ec0c6aca2",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/loop_safari.flac"
  },
  {
    "id": "tabla_dhec",
    "url": "/samples/tabla_dhec.mp3",
    "group": "percussion",
    "duration": 0.3250793650793651,
    "bytes": 4746,
    "sha256": "11756aaae5cbd08836b5135088872b6c5ee4898c061d9ffd52fffad02b99b031",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_dhec.flac"
  },
  {
    "id": "tabla_ghe1",
    "url": "/samples/tabla_ghe1.mp3",
    "group": "percussion",
    "duration": 0.5912244897959184,
    "bytes": 7880,
    "sha256": "39ac41bda90dd03156c580d5e19fff3ad7de00e51235edd121492047c0c05669",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_ghe1.flac"
  },
  {
    "id": "tabla_ghe2",
    "url": "/samples/tabla_ghe2.mp3",
    "group": "percussion",
    "duration": 2.6607256235827665,
    "bytes": 32644,
    "sha256": "2a373bc66b5ebdffd892b04752afe8d75c968342bde0757595cbda69090fb3f7",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_ghe2.flac"
  },
  {
    "id": "tabla_ke1",
    "url": "/samples/tabla_ke1.mp3",
    "group": "percussion",
    "duration": 0.04342403628117914,
    "bytes": 1297,
    "sha256": "10d886977645fe2adbff4fd3cbaeed6ba3c6a5a080b615625aa6b04456128e1a",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_ke1.flac"
  },
  {
    "id": "tabla_na",
    "url": "/samples/tabla_na.mp3",
    "group": "percussion",
    "duration": 0.7198185941043084,
    "bytes": 9448,
    "sha256": "66a62efd8646dc0fa7b715c0d11c9087395c483b3d7d41f1c6f302d97b1ffa8b",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_na.flac"
  },
  {
    "id": "tabla_na_o",
    "url": "/samples/tabla_na_o.mp3",
    "group": "percussion",
    "duration": 1.4889795918367348,
    "bytes": 18538,
    "sha256": "0d77666cd88d99a66fe6d8c187e09e5ede533e238390a3d8d6c9a421c7607bc1",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_na_o.flac"
  },
  {
    "id": "tabla_te1",
    "url": "/samples/tabla_te1.mp3",
    "group": "percussion",
    "duration": 0.17777777777777778,
    "bytes": 2865,
    "sha256": "d06394114f36f84cedbf292efa442282130105e332f287348dada01b0296c83e",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_te1.flac"
  },
  {
    "id": "tabla_tun1",
    "url": "/samples/tabla_tun1.mp3",
    "group": "percussion",
    "duration": 2.3394104308390022,
    "bytes": 28883,
    "sha256": "f3eeb877193e52ef0ebc89429d05f2c3e1130924a3485c8c1e9fb5ffcfde013b",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tabla_tun1.flac"
  },
  {
    "id": "vinyl_scratch",
    "url": "/samples/vinyl_scratch.mp3",
    "group": "texture",
    "duration": 0.27383219954648524,
    "bytes": 4119,
    "sha256": "0e38a9dfb1ee257a53054e0df8d91447a0a61b04e5875b8d23a2740fcb3e9e0b",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/vinyl_scratch.flac"
  },
  {
    "id": "vinyl_backspin",
    "url": "/samples/vinyl_backspin.mp3",
    "group": "texture",
    "duration": 1.06124716553288,
    "bytes": 13523,
    "sha256": "46ce1d657956c1ba8f23cf72e913e12e40c3605a936db055367174fffbc1e580",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/vinyl_backspin.flac"
  },
  {
    "id": "vinyl_rewind",
    "url": "/samples/vinyl_rewind.mp3",
    "group": "texture",
    "duration": 2.6804761904761905,
    "bytes": 32958,
    "sha256": "6488870b51187c5d0fb60bd9513409f068ffe18a6d4dc88462b8d2d9e5e44c23",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/vinyl_rewind.flac"
  },
  {
    "id": "glitch_perc1",
    "url": "/samples/glitch_perc1.mp3",
    "group": "texture",
    "duration": 1.836734693877551,
    "bytes": 22927,
    "sha256": "f35f6b3de2be7abff623a595ac196a9f5b91d38b14676ad00df4f5c859e5097c",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/glitch_perc1.flac"
  },
  {
    "id": "glitch_perc2",
    "url": "/samples/glitch_perc2.mp3",
    "group": "texture",
    "duration": 0.9278458049886621,
    "bytes": 11955,
    "sha256": "e53409a6a35dd2ee3dddb7a3c44e0f185f382f8c42a5f37df7f366d44431ec5c",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/glitch_perc2.flac"
  },
  {
    "id": "glitch_perc3",
    "url": "/samples/glitch_perc3.mp3",
    "group": "texture",
    "duration": 1.0909297052154194,
    "bytes": 13836,
    "sha256": "1a7033d46d7ae895c1322a78d63e159f2d4a1b720ce56e4a364b72b38ceec707",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/glitch_perc3.flac"
  },
  {
    "id": "glitch_perc4",
    "url": "/samples/glitch_perc4.mp3",
    "group": "texture",
    "duration": 0.9278684807256236,
    "bytes": 11955,
    "sha256": "fab6e4b545cd168acb10e50dde1541cad2c5cc4d57d2dc3d745cd2ab20b0e24a",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/glitch_perc4.flac"
  },
  {
    "id": "glitch_perc5",
    "url": "/samples/glitch_perc5.mp3",
    "group": "texture",
    "duration": 0.9278684807256236,
    "bytes": 11955,
    "sha256": "ae23e801fa4a8345bc6b31b984689f90afb297f9feaa9a3d65877031613fd171",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/glitch_perc5.flac"
  },
  {
    "id": "glitch_bass_g",
    "url": "/samples/glitch_bass_g.mp3",
    "group": "bass",
    "duration": 1.9310657596371883,
    "bytes": 23867,
    "sha256": "c23ea5b2e1bceaff60503bd66f3fc4c19cb49b2adc5585142ae6f56957ed5ec5",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/glitch_bass_g.flac"
  },
  {
    "id": "bass_drop_c",
    "url": "/samples/bass_drop_c.mp3",
    "group": "fx",
    "duration": 2.3589115646258505,
    "bytes": 29196,
    "sha256": "b5ede6456aae49426d595cd493848573ff18f0f336a8beb079fb5e003ee69050",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/bass_drop_c.flac"
  },
  {
    "id": "bass_hard_c",
    "url": "/samples/bass_hard_c.mp3",
    "group": "bass",
    "duration": 1.5,
    "bytes": 18852,
    "sha256": "c9be785be1f1ef41b0d7e400b74ded9564e957f213e98c4fa05a7405c10758e9",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/bass_hard_c.flac"
  },
  {
    "id": "bass_thick_c",
    "url": "/samples/bass_thick_c.mp3",
    "group": "bass",
    "duration": 3.9680725623582767,
    "bytes": 48318,
    "sha256": "79b4e61d3b1df00cc930a589710f54d7934cf384d8a8a15967325705fda4204e",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/bass_thick_c.flac"
  },
  {
    "id": "tbd_pad_1",
    "url": "/samples/tbd_pad_1.mp3",
    "group": "texture",
    "duration": 2,
    "bytes": 33061,
    "sha256": "5e5ffce9b321cdecb877f57cfe26da99fd46fa30e96b35ab870fb2217b05e0b3",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tbd_pad_1.flac"
  },
  {
    "id": "tbd_pad_2",
    "url": "/samples/tbd_pad_2.mp3",
    "group": "texture",
    "duration": 3.2025396825396824,
    "bytes": 52287,
    "sha256": "2f538396b5964468727b634f4004d539b9e5b35386adce1deeeb932c52f18660",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tbd_pad_2.flac"
  },
  {
    "id": "tbd_pad_3",
    "url": "/samples/tbd_pad_3.mp3",
    "group": "texture",
    "duration": 2.9826757369614514,
    "bytes": 48944,
    "sha256": "d4bbd45d4994d9cf83b3128e24264e633aa4d1952d64544e79436221d9fe3082",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tbd_pad_3.flac"
  },
  {
    "id": "tbd_pad_4",
    "url": "/samples/tbd_pad_4.mp3",
    "group": "texture",
    "duration": 2.4723356009070296,
    "bytes": 40585,
    "sha256": "eb82675af62c2a1f9723207399cd564936e48c772f1114e1bba590c0c4b60ebd",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/tbd_pad_4.flac"
  },
  {
    "id": "ambi_drone",
    "url": "/samples/ambi_drone.mp3",
    "group": "texture",
    "duration": 4.40843537414966,
    "bytes": 71514,
    "sha256": "e23173490fd029d7f4e316b92d09d3de29f001fe5dbf39c15a0b0292ac0d6cb6",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/ambi_drone.flac"
  },
  {
    "id": "perc_swoosh",
    "url": "/samples/perc_swoosh.mp3",
    "group": "texture",
    "duration": 0.6185714285714285,
    "bytes": 8194,
    "sha256": "4e17187b9ed292137b4f183a5729f06fdc42c36bbf3e017f8099e9b07a7bc191",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/perc_swoosh.flac"
  },
  {
    "id": "perc_impact1",
    "url": "/samples/perc_impact1.mp3",
    "group": "fx",
    "duration": 1.1198866213151928,
    "bytes": 14150,
    "sha256": "aa44c1eed45d7cacd8096b067ea9f1241c895e4d196e5ef5fccbcc1a95b5656a",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/perc_impact1.flac"
  },
  {
    "id": "misc_cineboom",
    "url": "/samples/misc_cineboom.mp3",
    "group": "fx",
    "duration": 7.922675736961451,
    "bytes": 95965,
    "sha256": "41ad10f16a6b79b47f6ace8246bca820115bc17afc07e231fda36d723b9e05a2",
    "source": "https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/b1702c06bf80354b9135b2427e985777251641e0/etc/samples/misc_cineboom.flac"
  }
] as const;
export type SampleId=typeof SAMPLE_CATALOG[number]["id"];
