import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const revision='b1702c06bf80354b9135b2427e985777251641e0';
const names=[
 'bd_808','bd_haus','bd_fat','bd_boom','sn_dub','sn_dolf','sn_generic',
 'hat_bdu','hat_cab','hat_gem','hat_metal','hat_raw','hat_tap','drum_cymbal_open','drum_roll',
 'loop_amen','loop_breakbeat','loop_tabla','loop_safari',
 'tabla_dhec','tabla_ghe1','tabla_ghe2','tabla_ke1','tabla_na','tabla_na_o','tabla_te1','tabla_tun1',
 'vinyl_scratch','vinyl_backspin','vinyl_rewind','glitch_perc1','glitch_perc2','glitch_perc3','glitch_perc4','glitch_perc5',
 'glitch_bass_g','bass_drop_c','bass_hard_c','bass_thick_c','tbd_pad_1','tbd_pad_2','tbd_pad_3','tbd_pad_4','ambi_drone','perc_swoosh','perc_impact1','misc_cineboom',
];
const root=path.resolve('public/samples'),cache=path.resolve('.sample-tools/sources');fs.mkdirSync(root,{recursive:true});fs.mkdirSync(cache,{recursive:true});
const binaries=path.resolve('.sample-tools/imageio_ffmpeg/binaries');
const bundled=fs.existsSync(binaries)?fs.readdirSync(binaries).find(n=>n.endsWith('.exe')):undefined;
const ffmpeg=process.env.SAMPLE_FFMPEG??(bundled?path.join(binaries,bundled):undefined);
if(!ffmpeg)throw Error('Set SAMPLE_FFMPEG to an FFmpeg executable, or install imageio-ffmpeg into .sample-tools.');
function run(args){const r=spawnSync(ffmpeg,args,{maxBuffer:64*1024*1024});if(r.status!==0)throw Error(r.stderr?.toString()??r.error?.message);return r.stdout;}
function group(name){if(/^(bd_|sn_|hat_|drum_|loop_amen|loop_breakbeat)/.test(name))return 'drums';if(/^(tabla_|loop_tabla|loop_safari)/.test(name))return 'percussion';if(/^(bass_drop|misc_cineboom|perc_impact)/.test(name))return 'fx';if(/^(bass_|glitch_bass)/.test(name))return 'bass';return 'texture';}
const catalog=[];
for(const name of names){
 const source='https://raw.githubusercontent.com/sonic-pi-net/sonic-pi/'+revision+'/etc/samples/'+name+'.flac';
 const original=path.join(cache,name+'.flac'),target=path.join(root,name+'.mp3');
 if(!fs.existsSync(original)){const r=await fetch(source,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(name+': '+r.status);fs.writeFileSync(original,Buffer.from(await r.arrayBuffer()));}
 if(!fs.existsSync(target))run(['-hide_banner','-loglevel','error','-y','-i',original,'-map_metadata','-1','-ar','44100','-c:a','libmp3lame','-b:a',/^(loop_|tbd_|ambi_)/.test(name)?'128k':'96k',target]);
 const pcm=run(['-hide_banner','-loglevel','error','-i',target,'-ac','1','-ar','44100','-f','f32le','pipe:1']);
 const data=fs.readFileSync(target);catalog.push({id:name,url:'/samples/'+name+'.mp3',group:group(name),duration:pcm.length/4/44100,bytes:data.length,sha256:createHash('sha256').update(data).digest('hex'),source});
 console.log(name+' '+data.length+' bytes');
}
fs.writeFileSync('lib/sample-catalog.ts','// Generated by scripts/download-samples.mjs; pinned CC0 Sonic Pi assets.\nexport const SAMPLE_CATALOG='+JSON.stringify(catalog,null,2)+' as const;\nexport type SampleId=typeof SAMPLE_CATALOG[number]["id"];\n');
const license='https://github.com/sonic-pi-net/sonic-pi/blob/'+revision+'/etc/samples/README.md';
fs.writeFileSync(path.join(root,'CREDITS.md'),'# Sonic Pi sample credits\n\nEvery sample below is public domain under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/), as documented in [Sonic Pi’s sample README]('+license+'). Downloaded from sonic-pi-net/sonic-pi at revision '+revision+'. Original FLAC files were converted to MP3 (44.1 kHz, 96 kbps; loops/pads/drone 128 kbps). No source audio was synthesized or substituted.\n\n| File | Source | License |\n| --- | --- | --- |\n'+catalog.map(s=>'| '+s.id+'.mp3 | [Original FLAC]('+s.source+') | CC0 1.0 |').join('\n')+'\n\nRepository naming: glitch_perc1–5 and perc_impact1 correspond to the requested glitch_perc_1–5 and perc_impact_1.\n');
console.log('TOTAL',catalog.length,'samples',catalog.reduce((sum,s)=>sum+s.bytes,0),'audio bytes');
